language: python

python: 2.7

install:
  - "pip install -r client/requirements.txt"
  - "pip install -r server/requirements.txt"
  - pip install coveralls

script:
  - cd client
  - nosetests --with-coverage
  - cd ../server
  - nosetests --with-coverage

notifications:
    email: false

after_success:
    coveralls